name: Run Python Script Weekly

on:
  schedule:
    - cron: "30 4 * * 0"   # every Sunday at 04:30 UTC
  workflow_dispatch:         # allows manual run from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python yellowpages_hammer_unions.py
